import type { MetadataRoute } from 'next'

// PWA manifest so the app installs cleanly via "Add to Home Screen" on Android.
// Icons are generated by app/icon.tsx and app/apple-icon.tsx at build time.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Security+ Coach',
    short_name: 'Sec+ Coach',
    description: 'CompTIA Security+ SY0-701 study coach',
    start_url: '/',
    display: 'standalone',
    background_color: '#0d0d15',
    theme_color: '#0d0d15',
    icons: [
      { src: '/icon', sizes: '512x512', type: 'image/png', purpose: 'any' },
      { src: '/apple-icon', sizes: '180x180', type: 'image/png' },
    ],
  }
}
